"""Regenerate the Apps Script form and shared email template from the working survey."""
from pathlib import Path
import base64
import re

folder = Path(__file__).resolve().parent
root = folder.parent
source = (folder / 'original-survey.html').read_text(encoding='utf-8')
start = source.index('const esc =')
end = source.index('const blank =', start)
template = source[start:end].rstrip() + '\n'
(folder / 'EmailTemplate.gs').write_text(
    '// Generated by build.py from the original email template.\n' + template,
    encoding='utf-8'
)
page = source[:start] + source[end:]
page = re.sub(r'<script src="[^"]*@emailjs[^"]*"></script>\s*', '', page)
page = re.sub(r'^const (?:PK|SVC|TPL)\s*=.*\n', '', page, flags=re.M)
page = re.sub(r'^const LOGO =.*\n', '', page, flags=re.M)
logo = base64.b64encode((root / 'OIP.jpg').read_bytes()).decode('ascii')
page = page.replace('encodeURI("OIP.jpg")', '"data:image/jpeg;base64,' + logo + '"')
page = page.replace('const { useState } = React;', 'const { useState, useRef } = React;')
page = page.replace('  const [sub, setSub] = useState(false);', '''  const [sub, setSub] = useState(false);
  const sending = useRef(false);
  const submissionId = useRef(crypto.randomUUID());''')
page = page.replace('  const submit = async () => {', '''  const submit = async () => {
    if (sending.current) return;''')
page = page.replace('const r=rec(); setBusy(true);', 'const r=rec(); sending.current=true; setBusy(true);')
send_start = page.index('      emailjs.init(')
send_end = page.index('      const up=', send_start)
page = page[:send_start] + '''      if (!window.google || !google.script || !google.script.run) {
        throw new Error("Please open the deployed Google Apps Script survey link.");
      }
      const result = await new Promise((resolve,reject) => {
        google.script.run.withSuccessHandler(resolve).withFailureHandler(reject)
          .submitSurvey(r,submissionId.current);
      });
      if (!result || result.ok !== true) throw new Error("The server did not confirm sending. Please try again.");
      r.submittedAt = result.submittedAt;
''' + page[send_end:]
page = page.replace('    setBusy(false);', '    sending.current=false; setBusy(false);')
page = page.replace('const reset = () => {', 'const reset = () => {submissionId.current=crypto.randomUUID();')
(folder / 'Index.html').write_text(page, encoding='utf-8')
print('Generated Index.html and EmailTemplate.gs')
