// Generated by build.py from the original email template.
const esc = (v="") => String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;");
const nl2br = (v="") => esc(v).replace(/\r?\n/g,"<br/>");
const fmtDate = (val) => { const d = val ? new Date(val) : new Date(); return isNaN(d.getTime()) ? esc(val||"") : d.toLocaleString("en-US",{month:"numeric",day:"numeric",year:"numeric",hour:"numeric",minute:"2-digit",second:"2-digit"}); };

const emailHTML = (r) => {
  const validation = Math.max(1,Math.min(5,parseInt(r.validationRating,10)||1));
  const fas = Math.max(1,Math.min(5,parseInt(r.fasRating,10)||1));
  const likelihood = Math.max(0,Math.min(10,parseInt(r.likelihood,10)||0));
  const sat = String(r.satisfaction||"").trim();
  const satMeta = {"Very dissatisfied":{bg:"#b45309",fg:"#fff"},"Dissatisfied":{bg:"#dc2626",fg:"#fff"},"Neutral":{bg:"#9ca3af",fg:"#fff"},"Satisfied":{bg:"#1d4ed8",fg:"#fff"},"Very satisfied":{bg:"#11796f",fg:"#fff"}}[sat]||{bg:"#9ca3af",fg:"#fff"};

  const answerBox = (val) => `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;margin-top:8px;"><tr><td style="background:#f5f8fc;border:1px solid #e5edf6;border-radius:10px;padding:13px 15px;font-size:14px;line-height:1.55;color:#12233f;">${val ? nl2br(val) : "<span style='color:#8a97a6;'>No response</span>"}</td></tr></table>`;
  const pill = (text,bg,fg) => `<span style="display:inline-block;background:${bg};color:${fg};border:1px solid ${bg};padding:6px 12px;border-radius:999px;font-size:13px;font-weight:700;line-height:1.2;">${esc(text)}</span>`;
  const miniPill = (text,on) => `<span style="display:inline-block;min-width:34px;text-align:center;padding:8px 0;margin:0 4px 6px 0;border-radius:7px;font-size:13px;font-weight:700;background:${on?"#2f4f95":"#f7f9fd"};color:${on?"#fff":"#7b8ca5"};border:1px solid ${on?"#2f4f95":"#d8e1ee"};">${esc(String(text))}</span>`;
  const chips = (raw) => { const items=String(raw||"").split(";").map(s=>s.trim()).filter(Boolean); if(!items.length) return "<span style='color:#8a97a6;font-size:14px;'>No response</span>"; return items.map(item=>`<span style="display:inline-block;margin:0 6px 6px 0;padding:5px 11px;border-radius:999px;border:1px solid #bfd3ee;background:#eef5ff;color:#1c4ea3;font-size:13px;line-height:1.2;">${esc(item)}</span>`).join(""); };
  const contactCell = (label,val) => `<td width="50%" valign="top" style="padding:0 10px 14px 0;"><div style="font-size:11px;letter-spacing:.5px;text-transform:uppercase;color:#7e8ea8;font-weight:700;margin-bottom:4px;">${label}</div><div style="font-size:15px;line-height:1.5;color:#12233f;">${val||"<span style='color:#8a97a6;'>—</span>"}</div></td>`;
  const section = (title) => `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;margin-top:22px;"><tr><td style="font-size:12px;letter-spacing:.6px;text-transform:uppercase;color:#234a8f;font-weight:700;padding-bottom:8px;">${title}</td></tr>`;

  return `<!doctype html><html><body style="margin:0;padding:0;background:#f4f7fb;font-family:Arial,Helvetica,sans-serif;color:#12233f;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;background:#f4f7fb;">
<tr><td align="center" style="padding:24px 12px;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:720px;border-collapse:collapse;background:#fff;border:1px solid #e6edf5;box-shadow:0 10px 24px rgba(17,31,53,.08);">
<tr><td style="background:#234a8f;padding:20px 24px;color:#fff;">
  <div style="font-size:19px;font-weight:700;line-height:1.25;">New Survey Response</div>
  <div style="margin-top:7px;font-size:13px;color:#eaf1ff;">Submitted ${fmtDate(r.submittedAt)}</div>
</td></tr>
<tr><td style="padding:24px;">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;">
    <tr><td style="background:#f7fafe;border:1px solid #e5edf6;border-radius:12px;padding:18px 18px 10px;">
      <div style="font-size:12px;letter-spacing:.6px;text-transform:uppercase;color:#234a8f;font-weight:700;margin-bottom:14px;">Contact Information</div>
      <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;">
        <tr>${contactCell("Full Name","<strong>"+esc(r.name)+"</strong>")}${contactCell("Organization","<strong>"+esc(r.org)+"</strong>")}</tr>
        <tr>${contactCell("Email","<a href='mailto:"+esc(r.email)+"' style='color:#1c4ea3;text-decoration:none;'>"+esc(r.email)+"</a>")}${contactCell("Role / Title",esc(r.role||""))}</tr>
      </table>
    </td></tr>
  </table>
  ${section("Q1 &mdash; How They Found Us")}<tr><td>${answerBox(r.source)}</td></tr></table>
	  ${section("Q2 &mdash; Validation")}<tr><td style="padding-bottom:8px;">${Array.from({length:5},(_,i)=>miniPill(i+1,i+1===validation)).join("")}<span style="margin-left:8px;font-size:14px;font-weight:700;color:#234a8f;">${validation}/5</span></td></tr><tr><td>${answerBox(r.validationComment)}</td></tr></table>
	  ${section("Q3 &mdash; FAS Rating")}<tr><td style="font-size:14px;line-height:1.5;margin-bottom:8px;"><strong>FAS:</strong> ${esc(r.fasName||"No response")}</td></tr><tr><td style="padding-bottom:8px;">${Array.from({length:5},(_,i)=>miniPill(i+1,i+1===fas)).join("")}<span style="margin-left:8px;font-size:14px;font-weight:700;color:#234a8f;">${fas}/5</span></td></tr><tr><td>${answerBox(r.fasComment)}</td></tr></table>
	  ${section("Q4 &mdash; Workflow Suggestions")}<tr><td>${answerBox(r.workflowSuggestions)}</td></tr></table>
	  ${section("Q5 &mdash; Overall Satisfaction")}<tr><td>${pill(sat||"No response",satMeta.bg,satMeta.fg)}</td></tr></table>
	  ${section("Q6 &mdash; Products Interested In")}<tr><td>${chips(r.productsInterested)}</td></tr></table>
	  ${section("Q7 &mdash; Likelihood To Recommend")}<tr><td style="padding-bottom:8px;"><span style="font-size:13px;font-weight:700;color:#11796f;margin-right:10px;">Likely</span>${Array.from({length:11},(_,i)=>10-i).map(n=>miniPill(n,n===likelihood)).join("")}<span style="margin-left:10px;font-size:13px;font-weight:700;color:#b42318;">Unlikely</span><span style="margin-left:8px;font-size:14px;font-weight:700;color:#234a8f;">${likelihood}/10</span></td></tr></table>
</td></tr>
</table>
</td></tr></table>
</body></html>`;
};
